language: node_js
node_js:
- '4'
- '6'
- '8'
env:
  matrix:
  - FEATURE=test
cache:
  directories:
  - node_modules
  - integration-tests/target
  - "$HOME/.cargo"
script:
- grunt
- node examples/map-proof.js
jobs:
  include:
  - env: FEATURE=integration
    language: rust
    rust: nightly-2018-05-19
    before_install:
    - nvm install 8 && nvm use 8
    - node --version
    - npm --version
    install:
    - npm install
    - npm run integration:build
    script:
    - npm run integration:unix
    after_script:
    - npm run postintegration:unix
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: exonum.bitfury@gmail.com
  api_key:
    secure: VxkJ9MOhWfpudp1LWnsOEmYe9rFZjDIP9cjtvtEcUT8TY5nhioYtmQc5udDtddiWrvTF1Zp7wBUjAs/MokR3ud7Bx8vyX3EvHhiG7mnLid0ZkqK/yR0X3ogmNEfCMSJPx9LbHamJwY6+iJ4Uiok1Lots6uD0Mx0XCYQWAAWY/oWDtXOxvIcQqBr+LTdkYk/nIPWo/AVUNRO/2Z7S1qmzaQKA7hwOwOakkjATjGBchgtK98Euy6p/m7FDR1jWwWxFP8A8ZpBP3xkq8GyeNENmiGQ62OJbmL/cXUoJf40B1ZTDEj6xEjt5NxjQAAm5BGXWtd3OHt9FZrNW6Cx+bvwvhPnPTIVSXTWuYe4TGcsNEbvYwOrGsbtqe+wnNc1qiK5N0iyhjHaG+AJs7f/m6OkIUIkXk3tcK38Bc0wnSlAiOM4AorkDQKPQH3G/Ir2wlVPpBAGTHsP8eq486mgLoRMvhRQAHL65nnsU1vEitkliEiDtRp14tQLfNYiY9i0cqy8ViZVDfPKMblOx9g8D2M26slrMAEa7DUcqzK3xS5MMLhymka4/5qz7FnPpUws8V9TR/E4QLpIPafBzg1NrFCHK+2lxABBRUdM+ZitcCbPJzJMXqZfifFwyt+BTlszMxOUqqd+bOZZC7nYKFcam+YioF19c24UEzoA8gl0tPLNCJmQ=
  on:
    tags: true
    repo: exonum/exonum-client
    node: '8'
