language: node_js
node_js:
- '4'
- '6'
- '8'

env:
  matrix:
  - FEATURE=test

cache:
  directories:
  - node_modules
  - integration-tests/target
  - $HOME/.cargo

script:
- grunt
- node examples/map-proof.js

jobs:
  include:
    - env: FEATURE=integration
      language: rust
      rust: nightly-2018-05-19
      before_install:
      - nvm install 8 && nvm use 8
      - node --version
      - npm --version
      install:
      - npm install
      # Compile the server beforehand
      - npm run integration:build
      script:
      - npm run integration:unix
      after_script:
      - npm run postintegration:unix

deploy:
  skip_cleanup: true
  provider: npm
  email: exonum.bitfury@gmail.com
  api_key:
    secure: E/wmYXsUnO7JGZceT2lvA33zkvGsZ5tyOSqJ+QrYYxQy4T+IyJdYAg54la4t/KQf8FwZ44FFdWeP16lbnh2HaWeOFbWK68RZNqpNVsDcL3BKPpcHotkVk5TeGzg1dsHYz0AN1rKkCLK1dDltN/gIyEGkgonA7mPgFJeCGAIXoLm+EPq05CGNPDkuZ4Hz8XsyCNHZsSI5X7vjnTKyx2nTIkqujHPsU8sk+PyNe+5EqVvB4wwQkvwu5P2zzLB9La4C8LXC6LNMtTp6Dbs5azvILrdddNt6in6nWwwffktX1Lza01aFn7nuibz0QL89A08Rju1ez6VXOesDOFqKMkckPWd34gUThbmMU/YlQBFFXMJHfcNUnVEY1NEYipBQ8YUYQ2JrUza5Oi+nBoP0oTtGWY57CH8ZbLy2k5dkVEB7Bainr7t9R3kFuZLcvuPpYjbzsHBn2sCdTl7RfWkSUTNODkaTJrwxRFa4EUj+9qokY/NAaWKSu3+kF0D+bPa5EOu1yEWaQiqP6gNF7jsFLdVLUciB1qz1YHFJPWySv1ivkLHP9fYoR2H8yHeCG6Wc1xJvLyWhqU5laaxdtI9SaylBw8t5rkpznlL7031jK2SaMCPdWiRgnfLb8vVmaNF0CZMKME77CazrX+Wb0ZOHyJyXcoH3dYRf0pRnFktojndatwA=
  on:
    branch: master
    tags: true
    node: '8'
after_success:
- npm run coveralls
